version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "fix(deps)"
      include: "scope"
    allow:
      - dependency-type: "all"

  # Frontend (React)
  - package-ecosystem: "npm"
    directory: "/client-app"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "fix(deps)"
      include: "scope"
    allow:
      - dependency-type: "all"

  # Backend (Node)
  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "fix(deps)"
      include: "scope"
    allow:
      - dependency-type: "all"

  # Optional: GitHub Actions workflow updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
