version: "3.8"

services:
  mdma-database:
    build: ./docker-files/database
    image: mdma-database-image:latest 
    container_name: mdma-database-container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin 
    volumes:
      - postgres_data:/var/lib/postgresql/data1
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d mdma -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  mdma-frontend: 
    build: ./client-app
    image: mdma-frontend-image:latest
    container_name: mdma-frontend-container
    environment:
      REACT_APP_BACKEND_API_BASE_URL: "http://localhost:5050/"
    volumes:
      - /app/node_modules
      - ./client-app:/app
    ports: 
      - 3000:3000
    depends_on:
      - mdma-backend

  mdma-backend:
    build: ./server
    image: mdma-backend-image:latest
    container_name: mdma-backend-container
    environment:
      DATABASE_URL: "postgresql://admin:admin@mdma-database-container:5432/mdma" # localhost change to container name
      PORT: 5000
      AZURE_STORAGE_ACCOUNT_NAME: "mdmaproject"
      AZURE_STORAGE_ACCESS_KEY: "z7XgEdiuZk3t0T4rQ9A1U4+gML1Nih2xazcE5J9XoBcQ64AYnmcVr8NOzTlhVRVv4w=="
    ports:
      - 5050:5000
    depends_on:
      mdma-database:
        condition: service_healthy

volumes:
  postgres_data:
