version: "3.8"

services:
  mdma-database:
    build: ./docker-files/database  # Build the image from the current directory (./)
    image: mdma-database-image:latest  # Tag the built image as "mdma-database:latest"
    container_name: mdma-database-container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin  # Consider replacing with a secure password
      DATABASE_NAME: mdma
    volumes:
      - postgres_data:/var/lib/postgresql/data1
    ports:
      - "5432:5432"
  frontend: 
    build: ./client-app
    environment:
      REACT_APP_BACKEND_API_BASE_URL: "http://localhost:5050/"
    ports: 
      - 3000:3000
    depends_on:
      - backend
  backend:
    build: ./server
    environment:
      DATABASE_URL: "postgresql://admin:admin@localhost:5432/mdma" # localhost change to container name
      PORT: 5000
      AZURE_STORAGE_ACCOUNT_NAME: "mdmaproject"
      AZURE_STORAGE_ACCESS_KEY: "z7XgEdiuZk3t0T4rQ9A1U4+gML1Nih2xazcE5J9XoBcQ64AYnmcVr8NOzTlhVRVv4w=="
    ports:
      - 5050:5000
    depends_on:
      - database

volumes:
  postgres_data:
  postgres_conf:  # New volume for configuration
