name: React Client CI

on:
  push:
    branches: [ main, test-github-workflows, 19-set-up-a-cicd-pipeline-for-triggering-tests ]
  pull_request:
    branches: [ main, test-github-workflows, 19-set-up-a-cicd-pipeline-for-triggering-tests ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd client-app && npm install
    - run: cd client-app && npm test
      env:
        CI: true
